// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoI2GJNsS6X8R3PiM0iykUwa9nnYFHb2c',
    appId: '1:865069004490:web:8553be3c4b999c0840a633',
    messagingSenderId: '865069004490',
    projectId: 'flutter-crud-firebase-a1c08',
    authDomain: 'flutter-crud-firebase-a1c08.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-a1c08.firebasestorage.app',
    measurementId: 'G-BK1Q3R4P7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoFjK-R4JQ66TP8b9jzQTvYgi0DcCaqSM',
    appId: '1:865069004490:android:f8d978b75af1c96640a633',
    messagingSenderId: '865069004490',
    projectId: 'flutter-crud-firebase-a1c08',
    storageBucket: 'flutter-crud-firebase-a1c08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjwSN66sjNb7zS4FtXiF5kkaONy3X1pSI',
    appId: '1:865069004490:ios:7bac8c8d187e133a40a633',
    messagingSenderId: '865069004490',
    projectId: 'flutter-crud-firebase-a1c08',
    storageBucket: 'flutter-crud-firebase-a1c08.firebasestorage.app',
    iosBundleId: 'com.example.modul9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjwSN66sjNb7zS4FtXiF5kkaONy3X1pSI',
    appId: '1:865069004490:ios:7bac8c8d187e133a40a633',
    messagingSenderId: '865069004490',
    projectId: 'flutter-crud-firebase-a1c08',
    storageBucket: 'flutter-crud-firebase-a1c08.firebasestorage.app',
    iosBundleId: 'com.example.modul9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoI2GJNsS6X8R3PiM0iykUwa9nnYFHb2c',
    appId: '1:865069004490:web:ccdab261fa426eaf40a633',
    messagingSenderId: '865069004490',
    projectId: 'flutter-crud-firebase-a1c08',
    authDomain: 'flutter-crud-firebase-a1c08.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-a1c08.firebasestorage.app',
    measurementId: 'G-SPGNX77RVC',
  );

}